/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/$chatId'
import { Route as AuthenticatedChatIdSettingsRouteImport } from './routes/_authenticated/$chatId_.settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdSettingsRoute =
  AuthenticatedChatIdSettingsRouteImport.update({
    id: '/$chatId_/settings',
    path: '/$chatId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$chatId': typeof AuthenticatedChatIdRoute
  '/$chatId/settings': typeof AuthenticatedChatIdSettingsRoute
}
export interface FileRoutesByTo {
  '/$chatId': typeof AuthenticatedChatIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/$chatId/settings': typeof AuthenticatedChatIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$chatId': typeof AuthenticatedChatIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$chatId_/settings': typeof AuthenticatedChatIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chatId' | '/$chatId/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/$chatId' | '/' | '/$chatId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$chatId'
    | '/_authenticated/'
    | '/_authenticated/$chatId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$chatId': {
      id: '/_authenticated/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$chatId_/settings': {
      id: '/_authenticated/$chatId_/settings'
      path: '/$chatId/settings'
      fullPath: '/$chatId/settings'
      preLoaderRoute: typeof AuthenticatedChatIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatIdSettingsRoute: typeof AuthenticatedChatIdSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatIdSettingsRoute: AuthenticatedChatIdSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
